CXX = g++
CXXFLAGS = -std=c++17 -Wall -Iinclude

SRCS = src/delivery.cpp src/file_io.cpp src/hash_table.cpp src/main.cpp src/priority_queue.cpp src/quadtree.cpp src/road_network.cpp src/route_optimizer.cpp src/scheduler.cpp src/utils.cpp
OBJS = $(SRCS:.cpp=.o)

EXEC = smart_city

build: $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(EXEC) $(OBJS)

run: build
	./$(EXEC)